[build]
  command = "npm run build"
  publish = "dist/public"
  functions = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "dist"

[dev]
  command = "npm run dev"
  port = 5173
  targetPort = 5173

# Environment variables for production
[build.environment]
  VITE_SUPABASE_URL = "https://lwqeysdqcepqfzmwvwsq.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx3cWV5c2RxY2VwcWZ6bXd2d3NxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMjQ3OTksImV4cCI6MjA3MzYwMDc5OX0.5B6Jnpqh7zEIHHABF13ylltIZgttJ-ZKHC6AgzSMKlc"
  NODE_ENV = "production"